apiVersion: v1
kind: Service
metadata:
  name: hospital-backend
  labels:
    app.kubernetes.io/name: hospital-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: hospital
spec:
  selector:
    app.kubernetes.io/name: hospital-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
