# These ExternalSecrets are automatically synced from AWS Secrets Manager by the External Secrets Operator.
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: be-db-es
  namespace: hospital-prod
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: be-db-secret
  data:
  - secretKey: default-connection
    remoteRef:
      key: hospital-be-db
      property: default-connection
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: be-jwt-es
  namespace: hospital-prod
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: be-jwt-secret
  data:
  - secretKey: secret
    remoteRef:
      key: hospital-be-jwt
      property: secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: be-redis-es
  namespace: hospital-prod
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: be-redis-secret
  data:
  - secretKey: password
    remoteRef:
      key: hospital-be-redis
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-auth-es
  namespace: hospital-prod
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: redis-auth-secret
  data:
  - secretKey: password
    remoteRef:
      key: hospital-redis-auth
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexus-registry-es
  namespace: hospital-prod
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nexus-registry-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths": {"100.112.150.56:8082": {"username": "{{ .nexus_user }}", "password": "{{ .nexus_password }}", "auth": "{{ printf "%s:%s" .nexus_user .nexus_password | b64enc }}"}}}'
  data:
  - secretKey: nexus_user
    remoteRef:
      key: hospital-nexus-registry
      property: username
  - secretKey: nexus_password
    remoteRef:
      key: hospital-nexus-registry
      property: password
