apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hospital-prod

resources:
  - namespace.yaml
  - external-secrets.yaml
  - ../../base

replicas:
  - name: fe-deployment-v1
    count: 3
  - name: be-deployment-v1
    count: 3

images:
  - name: 100.112.150.56:8082/ecr-fe
    newName: 100.112.150.56:8082/ecr-fe
    newTag: 8867f93a0c075e0782936bd07355d7f6ea044995
  - name: 100.112.150.56:8082/ecr-be
    newName: 100.112.150.56:8082/ecr-be
    newTag: 8867f93a0c075e0782936bd07355d7f6ea044995
