apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hospital-prod

resources:
  - namespace.yaml
  - external-secrets.yaml
  - ../../base

replicas:
  - name: fe-deployment-v1
    count: 3
  - name: be-deployment-v1
    count: 3

images:
  - name: 100.112.150.56:8082/ecr-fe
    newName: 100.112.150.56:8082/ecr-fe
    newTag: d13e8a4f7dfbd4f6cfa03abcf5e3844a78d2e91a
  - name: 100.112.150.56:8082/ecr-be
    newName: 100.112.150.56:8082/ecr-be
    newTag: d13e8a4f7dfbd4f6cfa03abcf5e3844a78d2e91a
