apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: logging-config
    app.kubernetes.io/part-of: platform
spec:
  project: platform
  source:
    repoURL: https://github.com/Kien-devops/k8s-home.git
    targetRevision: main
    path: deploy/platform/observability/logging
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
