apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hospital-frontend-stag
  namespace: argocd
  labels:
    app.kubernetes.io/name: hospital-frontend
    app.kubernetes.io/part-of: hospital
spec:
  project: hospital
  source:
    repoURL: https://github.com/Kien-devops/k8s-home.git
    targetRevision: main
    path: deploy/workloads/hospital-frontend/overlays/stag
  destination:
    server: https://kubernetes.default.svc
    namespace: hospital-stag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
