apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-monitoring
  namespace: monitoring
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "hospital-prod"
          serviceAccountRef:
            name: grafana-vault-auth
            audiences:
              - vault
