apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-db-es
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-monitoring
    kind: SecretStore
  target:
    name: grafana-db-secret
  data:
    - secretKey: password
      remoteRef:
        key: hospital/grafana-db
        property: password
