apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hospital-traefik-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kien-devops/k8s-onprem.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: hospital-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
