apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-prod
resources:
  - ../../base
  - gateway-route.yaml
patches:
  - path: patch-deployment.yaml
images:
  - name: 100.112.150.56:8082/ecr-fe
    newName: 100.112.150.56:8082/ecr-fe
    newTag: 49f7a0992a1fa1ef546e02a93b3084ea960d37c8
