apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hospital-stag
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
images:
  - name: 100.112.150.56:8082/ecr-be
    newName: 100.112.150.56:8082/ecr-be
    newTag: ea729165289e467954dc42f2cb0bc3597dc841c4
